version: '3'

services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server/data:/app/data
    environment:
      - CSV_FILE_PATH=/app/data/absence_periods.csv

  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5001
