version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: absence-calculator-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: absence_calculator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../server/data:/app/server/data
      - ../server:/app/server
    environment:
      - CSV_FILE_PATH=/app/server/data/absence_periods.csv
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=absence_calculator
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  postgres_data: