version: '3.8'
name: absence-calculator

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: absence-calculator-backend
    ports:
      - "5001:5001"
    volumes:
      - ../server/data:/app/data
    environment:
      - CSV_FILE_PATH=/app/data/absence_periods.csv
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/absence-periods"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: absence-calculator-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
    driver: local
