version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../server/data:/app/server/data
    environment:
      - CSV_FILE_PATH=/app/server/data/absence_periods.csv

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend